'use strict';

/**
 * Artillery Helper Functions
 * 
 * Provides dynamic data generation and token management
 * for the stress test scenarios.
 */

const fs = require('fs');
const path = require('path');

// Load test data generated by seed-stress.ts
let testData;
try {
  testData = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'test-data.json'), 'utf8')
  );
} catch (e) {
  console.error('❌ test-data.json not found. Run seed-stress.ts first.');
  process.exit(1);
}

// Token cache to avoid re-authenticating on every request
const tokenCache = new Map();

function randomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * Before-scenario hook: sets up random test data for each virtual user
 */
function setVariables(context, events, done) {
  // Random user selection
  const isProvider = Math.random() > 0.5;
  context.vars.userEmail = isProvider
    ? randomItem(testData.providerEmails)
    : randomItem(testData.clientEmails);
  context.vars.userPassword = testData.password;

  // Random provider & client for offer flows
  context.vars.providerEmail = randomItem(testData.providerEmails);
  context.vars.clientEmail = randomItem(testData.clientEmails);
  context.vars.providerPassword = testData.password;
  context.vars.clientPassword = testData.password;

  // Random existing IDs for GET/PATCH operations
  context.vars.randomJobPostId = randomItem(testData.jobPostIds);
  context.vars.randomCategoryId = randomItem(testData.categoryIds);
  context.vars.randomUserId = randomItem(testData.userIds);
  context.vars.randomPeerId = randomItem(testData.userIds);
  context.vars.randomOfferId = randomItem(testData.offerIds);
  context.vars.randomProviderId = randomItem(testData.providerIds);
  context.vars.randomClientId = randomItem(testData.clientIds);

  // Random pagination
  context.vars.randomPage = randomInt(1, 10);
  context.vars.randomLimit = randomItem([10, 20, 50]);

  // Random geo coordinates (Guatemala area)
  context.vars.randomLat = (13.7 + Math.random() * 4.1).toFixed(4);
  context.vars.randomLng = (-92.2 + Math.random() * 4.0).toFixed(4);

  // Random content for writes
  context.vars.uuid = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

  done();
}

/**
 * After-response hook: captures auth token from login response
 */
function captureToken(req, res, context, events, done) {
  if (res.statusCode === 200 || res.statusCode === 201) {
    try {
      const body = typeof res.body === 'string' ? JSON.parse(res.body) : res.body;
      if (body && body.access_token) {
        context.vars.token = body.access_token;
      }
    } catch (e) {
      // Response was not JSON — ignore
    }
  }
  done();
}

/**
 * After-response hook: captures token specifically for provider login
 */
function captureProviderToken(req, res, context, events, done) {
  if (res.statusCode === 200 || res.statusCode === 201) {
    try {
      const body = typeof res.body === 'string' ? JSON.parse(res.body) : res.body;
      if (body && body.access_token) {
        context.vars.providerToken = body.access_token;
      }
    } catch (e) {}
  }
  done();
}

/**
 * After-response hook: captures token specifically for client login
 */
function captureClientToken(req, res, context, events, done) {
  if (res.statusCode === 200 || res.statusCode === 201) {
    try {
      const body = typeof res.body === 'string' ? JSON.parse(res.body) : res.body;
      if (body && body.access_token) {
        context.vars.clientToken = body.access_token;
      }
    } catch (e) {}
  }
  done();
}

/**
 * Log non-2xx responses for debugging
 */
function logErrors(req, res, context, events, done) {
  if (res.statusCode >= 400) {
    const url = req.url || req.uri;
    const body = typeof res.body === 'string' ? res.body.slice(0, 200) : JSON.stringify(res.body).slice(0, 200);
    console.error(`[${res.statusCode}] ${req.method} ${url} → ${body}`);
  }
  done();
}

module.exports = {
  setVariables,
  captureToken,
  captureProviderToken,
  captureClientToken,
  logErrors,
};
